# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-15 14:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulo', '0002_auto_20170210_0448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='fecha_publicacion',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
