# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-18 00:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulo', '0002_auto_20170210_0448'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='pictures'),
        ),
    ]
